apiVersion: v1
kind: Secret
metadata:
  name: azdevops-pat
data:
  personalAccessToken: 'ang3dXE0dXJjZWM2cHV1em5xeWFhYmZvd2JqZnV5ZWd3c2s2bXdybWxubngzYnlseTJxcQo='
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ado-agent-deployment
  labels:
    app: azdevops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: adoimages.azurecr.io/ado-agent:db5        
        env:
          - name: AZP_URL
            value: "https://dev.azure.com/returngisorg" 
          - name: AZP_POOL
            value: "agents-on-aks"
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops-pat
                key: personalAccessToken
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"

