apiVersion: v1
kind: Secret
metadata:
  name: azdevops-pat
data:
  personalAccessToken: 'Cg=='
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ado-agent-deployment
  labels:
    app: azdevops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: adoimages.azurecr.io/ado-agent:
        requests:
          cpu: "1"
          memory: "2Gi"
        env:
          - name: AZP_URL
            value: "https://dev.azure.com/" 
          - name: AZP_POOL
            value: ""
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops-pat
                key: personalAccessToken
