FROM alpine

RUN apk update
RUN apk upgrade

ENV TARGETARCH="linux-musl-x64"

RUN apk add --update --no-cache \
    bash \
    curl \
    git \
    icu-libs \
    jq \
    wget \    
    openjdk17 \
    python3 \
    && ln -sf python3 /usr/bin/python 


# Install .NET using the script
RUN wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh \
    && chmod +x dotnet-install.sh \
    && ./dotnet-install.sh --version latest \
    && rm dotnet-install.sh

# Install Azure CLI
# RUN curl -L https://aka.ms/InstallAzureCli | bash

# ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV JAVA_HOME=/opt/openjdk-17

RUN export JAVA_HOME

WORKDIR /azp

COPY ./start.sh .
RUN chmod +x start.sh

# Create agent user and set up home directory
RUN adduser -D agent
RUN chown -R agent:agent /azp /home/agent

USER agent

ENTRYPOINT [ "./start.sh" ]