resources:
  repositories:
  - repository: MyDotNetRepo
    type: github
    endpoint: MyGitHubServiceConnection
    name: 0GiS0/tour-of-heroes-dotnet-api

trigger:
- main

pool: agents-on-aks

steps:
- checkout: MyDotNetRepo
- script: echo "Running this job on $(Agent.OS) with name $(Agent.Name) and version $(Agent.Version)"
  displayName: 'Showing OS of the agent'
- script: az version
  displayName: 'Showing Azure CLI version'
# - task: UseDotNet@2
#   inputs:
#     packageType: 'sdk'
#     version: '8.x'
- script: dotnet --help
  displayName: 'Check dotnet version'
- script: dotnet build --configuration Release
  displayName: 'Building the project'