trigger:
- windows-agents

pool: win-agents-on-aks

steps:
- checkout: git://WebApiDotNetFramework
- script: echo "Running this job on $(Agent.OS) with name $(Agent.Name) and version $(Agent.Version)"
- script: echo "Check working directory"
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: 'Showing OS of the agent'
- script: nuget restore WebApiDotNetFramework.sln
  displayName: 'Restoring NuGet packages'
- script: msbuild WebApiDotNetFramework.sln /p:Configuration=Release
- script: git --version
  displayName: 'Check git CLI installation'
  continueOnError: true
- script: jf --version
  displayName: 'Check jfrog-cli'
  continueOnError: true
- script: aws --version
  displayName: 'Check awscli installation'
  continueOnError: true
- script: az --version
  displayName: 'Check az cli installation'
  continueOnError: true
- script: azuresigntool --help
  displayName: 'Check sign cli installation'
  continueOnError: true
- script: sonar-scanner --version 
  displayName: 'Check sonarqube CLI installation'
  continueOnError: true
- script: java -version
  displayName: 'Check JDK 8 installation'
  continueOnError: true
- script: python --version
  displayName: 'Check Python installation'
  continueOnError: true
- script: openssl --version
  displayName: 'Check OpenSSL installation'
  continueOnError: true
- script: 7z --help
  displayName: 'Check 7zip installation'
  continueOnError: true